### ISSUE TITLE
[Bug] Loader Text Size Exeeds Maximum

### ISSUE THREAD

**Issue by PhlexPlexico** [RicBent/Magikoopa#4]
Hey there! I reported this in [Project Restoration](https://github.com/leoetlino/project-restoration/issues/250), but figured I may as well submit it to both repositories, since my own patch seems to be suffering from this as well, and I'm not longer able to compile it.

I'm trying to create a patch with Magikoopa with the latest version of libctru/devkitarm, and whenever I try to compile, it receives the aforementioned error, "Loader Text Size Exeeds Maximum". 

![image](https://github.com/RicBent/Magikoopa/assets/3514085/adb00701-3109-40a7-9500-0cc5141c7baa)

![image](https://github.com/RicBent/Magikoopa/assets/3514085/2b547aab-72df-40a9-9027-faf08a981c10)

I know I was able to compile this last year, but I believe the toolchain have received some updates since then, which may be the reason why it's failing now. If I'm able to build an older version of the toolchain I will see if I can get the build to succeed.

Thanks!

**Comment by RicBent** [comment]
I am almost sure that you accidentally put a pre-patched `exheader.bin` into the `bak` folder. An `exheader.bin` which is patched with Magikoopa will always produce an `exheader.bin` that will display 0 loader space.

Delete the `bak` folder and replace the `code.bin` and `exheader.bin` with clean files and lmk if that works.

An update to devkitPro/ARM shouldn't affect loader size detection at all as that is calculated without any involvement of that.

**Comment by PhlexPlexico** [comment]
Hey!

Thanks for the response! I guess my modified `exheader.bin` overwrote the original I was using! Looks like that fixed my issue!

Thanks!
